wrapper:
  # Options: [None, 'ddp', 'dp', 'ddp_spawn', 'horovod', 'tpu_spawn']
  type: ddp

  # The number of GPUs/nodes to use
  gpus: 1
  num_nodes: 1

  scheduler_kwargs:
    decay_steps: 128
    warmup_steps: 13

  optimizer_kwargs:
    lr: 0.001
    wd: 0.0001
    filter_by_requires_grad: true
  use_ema: true

trainer:
  max_steps: 128
  check_val_every_n_epoch: 2
  accumulate_grad_batches: 4

ckpt_path: checkpoints/epoch=00062.ckpt