wrapper:
  # Options: [None, 'ddp', 'dp', 'ddp_spawn', 'horovod', 'tpu_spawn']
  type: ddp

  # The number of GPUs/nodes to use
  gpus: 1
  num_nodes: 1

  scheduler_kwargs:
    decay_steps: 10

  optimizer_kwargs:
    lr: 0.001
    weight_decay: 0.0001

trainer:
  max_steps: 32
  check_val_every_n_epoch: 2